language: php

php:
  - '7.1'

sudo: false

before_script:
  - composer self-update && composer install

script:
  - mkdir -p var/logs
  - vendor/bin/phpunit -c phpunit.xml.dist

after_success:
  - travis_retry php vendor/bin/php-coveralls
